#spring.mvc.view.prefix=/pages/
#spring.mvc.view.suffix=.jsp

#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.url=jdbc:postgresql://localhost:5432/final_project
#spring.datasource.username=postgres
#spring.datasource.password=Punam@28
#spring.jpa.hibernate.ddl-auto=update


#spring.sql.init.mode=always
#spring.sql.init.data-locations=classpath:data.sql
#spring.jpa.defer-datasource-initialization=true


#server.tomcat.max-swallow-size=-1
#spring.servlet.multipart.max-file-size=10MB
#spring.servlet.multipart.max-request-size=10MB

#spring.jackson.serialization.fail-on-empty-beans=false




spring.mvc.view.prefix=/pages/
spring.mvc.view.suffix=.jsp

spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=jdbc:postgresql://localhost:5432/nbfc?sslmode=disable

spring.datasource.username=postgres
spring.datasource.password=8767950526

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update


spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql
spring.jpa.defer-datasource-initialization=true

server.tomcat.max-swallow-size=-1
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.jackson.serialization.fail-on-empty-beans=false